export default function KyronexDashboard() {
  const playSfx = (file: string) => {
    const audio = new Audio(`/kyronex/${file}`);
    audio.volume = 0.24;
    audio.play().catch(() => undefined);
  };

  return (
    <main className="kx-red">
      <style>{`
        .kx-red{--red:#ff2020;--red-soft:rgba(255,32,32,.16);--white:#f4f4f4;--dim:rgba(244,244,244,.5);min-height:100vh;overflow:hidden;position:relative;color:var(--white);background:#030304;font-family:"Space Mono","Courier New",monospace}
        .kx-red:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.13;background:linear-gradient(rgba(255,255,255,.08) 1px,transparent 1px);background-size:100% 4px;mix-blend-mode:screen}
        .kx-red:after{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(ellipse at center,transparent 38%,rgba(0,0,0,.7) 100%)}
        .kx-red-shell{position:relative;z-index:1;width:min(960px,calc(100% - 30px));margin:auto;padding:26px 0 30px}.kx-red-header{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:28px}.kx-red-brand{display:flex;align-items:center;gap:12px;color:var(--white);text-decoration:none}.kx-red-mark{width:34px;height:34px;display:grid;place-items:center;color:#080808;font-size:.7rem;font-weight:900;background:var(--red);box-shadow:0 0 18px rgba(255,0,0,.7);clip-path:polygon(50% 0,100% 25%,100% 75%,50% 100%,0 75%,0 25%)}.kx-red-title{font-size:.8rem;font-weight:700;letter-spacing:.25em}.kx-red-sub{display:block;margin-top:4px;color:rgba(255,32,32,.65);font-size:.52rem;letter-spacing:.16em}.kx-red-status{display:flex;align-items:center;gap:8px;color:var(--red);font-size:.58rem;letter-spacing:.12em}.kx-red-status i{width:6px;height:6px;border-radius:50%;background:var(--red);box-shadow:0 0 12px var(--red);animation:kx-pulse 1.1s ease-in-out infinite}
        .kx-red-hero{display:flex;align-items:end;justify-content:space-between;gap:24px;padding:18px 0 20px;border-top:1px solid rgba(255,32,32,.25);border-bottom:1px solid rgba(255,32,32,.25)}.kx-red-kicker{margin:0 0 10px;color:rgba(255,32,32,.72);font-size:.58rem;letter-spacing:.2em}.kx-red h1{margin:0;color:var(--white);font-size:clamp(1.7rem,5vw,3.3rem);line-height:1;letter-spacing:.03em;text-transform:uppercase;text-shadow:0 0 18px rgba(255,0,0,.3)}.kx-red-copy{max-width:270px;margin:0;color:var(--dim);font-size:.6rem;line-height:1.7;text-align:right}.kx-scanner{position:relative;height:10px;margin:12px 0 22px;overflow:hidden;background:rgba(255,32,32,.08);border:1px solid rgba(255,32,32,.22);box-shadow:0 0 18px rgba(255,0,0,.12)}.kx-scanner span{position:absolute;top:0;left:-18%;width:18%;height:100%;background:linear-gradient(90deg,transparent,var(--red),#fff,var(--red),transparent);box-shadow:0 0 18px 5px rgba(255,32,32,.8);animation:kx-scan 2.2s linear infinite}
        .kx-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.kx-card{--accent:var(--red);position:relative;display:flex;min-height:154px;flex-direction:column;justify-content:space-between;padding:16px;color:var(--white);overflow:hidden;text-decoration:none;border:1px solid rgba(255,32,32,.27);background:linear-gradient(140deg,rgba(38,6,8,.64),rgba(8,8,11,.44));backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);box-shadow:inset 0 0 28px rgba(255,0,0,.025),0 10px 30px rgba(0,0,0,.3);transition:transform .25s ease,border-color .25s ease,background .25s ease,box-shadow .25s ease}.kx-card:before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(105deg,transparent 35%,rgba(255,32,32,.18) 50%,transparent 65%);transform:translateX(-120%);transition:transform .6s ease}.kx-card:hover,.kx-card:focus-visible{border-color:var(--accent);background:linear-gradient(140deg,rgba(80,8,12,.72),rgba(14,8,12,.62));box-shadow:0 0 22px rgba(255,0,0,.22),inset 0 0 24px rgba(255,0,0,.08);transform:translateY(-4px)}.kx-card:hover:before,.kx-card:focus-visible:before{transform:translateX(120%)}.kx-card:focus-visible{outline:1px solid var(--red);outline-offset:3px}.kx-card:nth-child(2){--accent:#ff6b6b}.kx-card:nth-child(3){--accent:#ff3333}.kx-card:nth-child(4){--accent:#ff9b55}.kx-card:nth-child(5){--accent:#ff4545}.kx-card:nth-child(6){--accent:#d7d7d7}.kx-card-top,.kx-card-bottom{position:relative;z-index:1}.kx-card-top{display:flex;justify-content:space-between;align-items:start}.kx-index{color:var(--accent);font-size:.52rem;letter-spacing:.14em}.kx-icon{color:var(--accent);font-size:1.2rem;text-shadow:0 0 12px var(--accent)}.kx-card h2{margin:18px 0 7px;color:var(--white);font-size:1rem;letter-spacing:.05em}.kx-card p{margin:0;color:var(--dim);font-size:.57rem;line-height:1.55}.kx-card-bottom{display:flex;align-items:center;justify-content:space-between;margin-top:14px}.kx-card-state{color:var(--accent);font-size:.5rem;letter-spacing:.1em;text-transform:uppercase}.kx-open{color:var(--white);font-size:.54rem;letter-spacing:.08em}.kx-open b{color:var(--accent);font-size:.85rem}.kx-footer{display:flex;align-items:center;justify-content:space-between;margin-top:15px;padding-top:14px;color:rgba(244,244,244,.38);font-size:.5rem;letter-spacing:.12em;border-top:1px solid rgba(255,32,32,.2)}.kx-footer strong{color:rgba(255,32,32,.75);font-weight:400}@keyframes kx-scan{0%{left:-18%}100%{left:100%}}@keyframes kx-pulse{50%{opacity:.35;box-shadow:0 0 3px var(--red)}}@media(max-width:720px){.kx-red-hero{display:block}.kx-red-copy{max-width:100%;margin-top:13px;text-align:left}.kx-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.kx-red-shell{width:calc(100% - 22px);padding-top:18px}.kx-red-status{font-size:.48rem}.kx-red-title{font-size:.68rem}.kx-grid{gap:9px}.kx-card{min-height:148px;padding:13px}.kx-card h2{font-size:.82rem}.kx-card p{font-size:.5rem}.kx-footer{font-size:.43rem}}
      `}</style>
      <div className="kx-red-shell">
        <header className="kx-red-header"><a className="kx-red-brand" href="/kyronex/"><span className="kx-red-mark">KX</span><span><span className="kx-red-title">KYRONEX</span><span className="kx-red-sub">KNIGHT INDUSTRIES SYSTEM</span></span></a><span className="kx-red-status"><i />SYSTEM ONLINE</span></header>
        <section className="kx-red-hero"><div><p className="kx-red-kicker">NEURAL ACCESS TERMINAL // 06 UNITS</p><h1>Choose your unit</h1></div><p className="kx-red-copy">Interface centrale de pilotage. Sélectionnez une unité pour établir la liaison.</p></section>
        <div className="kx-scanner" aria-hidden="true"><span /></div>
        <section className="kx-grid" aria-label="Unités KYRONEX">
          <a className="kx-card" href="https://kitt.kitt-franco-belge.be" target="_blank" rel="noreferrer" onMouseEnter={() => playSfx("hover_kitt.mp3")}><span className="kx-card-top"><span className="kx-index">01 // CORE</span><span className="kx-icon">◈</span></span><span><h2>K1</h2><p>Unité centrale de première génération.</p></span><span className="kx-card-bottom"><span className="kx-card-state">READY</span><span className="kx-open">OPEN <b>›</b></span></span></a>
          <a className="kx-card" href="https://karr.kitt-franco-belge.be" target="_blank" rel="noreferrer" onMouseEnter={() => playSfx("hover_karr.mp3")}><span className="kx-card-top"><span className="kx-index">02 // ORIN</span><span className="kx-icon">⬡</span></span><span><h2>OR1NX16QN7B</h2><p>Orin NX 16 Go · calcul neural local.</p></span><span className="kx-card-bottom"><span className="kx-card-state">ONLINE</span><span className="kx-open">OPEN <b>›</b></span></span></a>
          <a className="kx-card" href="https://kitt.kitt-franco-belge.be" target="_blank" rel="noreferrer" onMouseEnter={() => playSfx("hover_kitt.mp3")}><span className="kx-card-top"><span className="kx-index">03 // AI</span><span className="kx-icon">✦</span></span><span><h2>KIT</h2><p>Interface conversationnelle K.I.T.T.</p></span><span className="kx-card-bottom"><span className="kx-card-state">READY</span><span className="kx-open">OPEN <b>›</b></span></span></a>
          <a className="kx-card" href="https://kitt.kitt-franco-belge.be" target="_blank" rel="noreferrer" onMouseEnter={() => playSfx("hover_kitt.mp3")}><span className="kx-card-top"><span className="kx-index">04 // FLAGSHIP</span><span className="kx-icon">⚡</span></span><span><h2>SUPER KIT V3</h2><p>Architecture flagship haute puissance.</p></span><span className="kx-card-bottom"><span className="kx-card-state">MAX POWER</span><span className="kx-open">OPEN <b>›</b></span></span></a>
          <a className="kx-card" href="http://192.168.129.25:3001?ai=karr_dadoo" target="_blank" rel="noreferrer" onMouseEnter={() => playSfx("hover_karr.mp3")}><span className="kx-card-top"><span className="kx-index">05 // DADOO</span><span className="kx-icon">◎</span></span><span><h2>Carte de Dadoo</h2><p>Nœud KARR · Jetson Orin NX.</p></span><span className="kx-card-bottom"><span className="kx-card-state">LOCAL NET</span><span className="kx-open">OPEN <b>›</b></span></span></a>
          <a className="kx-card" href="https://k4000.kitt-franco-belge.be" target="_blank" rel="noreferrer" onMouseEnter={() => playSfx("hover_kitt.mp3")}><span className="kx-card-top"><span className="kx-index">06 // KR-95</span><span className="kx-icon">◇</span></span><span><h2>K4000</h2><p>Unité KIRONEX · pilotage avancé.</p></span><span className="kx-card-bottom"><span className="kx-card-state">OPERATIONAL</span><span className="kx-open">OPEN <b>›</b></span></span></a>
        </section>
        <footer className="kx-footer"><span><strong>KYRONEX</strong> // NEURAL ACCESS TERMINAL</span><span>V3.0 · SECURE LINK</span></footer>
      </div>
    </main>
  );
}
