import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "fr" | "en";

interface LanguageContextType {
  lang: Lang;
  toggle: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Nav
    "nav.histoire": "histoire",
    "nav.services": "services",
    "nav.videos": "vidéos",
    "nav.avis": "avis",
    "nav.contact": "contact",
    "nav.karr": "KARR",
    "nav.soumettre": "SOUMETTRE",
    "nav.galerie": "GALERIE",
    "nav.musique": "MUSIQUE",
    "nav.docs": "DOCS",
    "nav.access": "ACCÉDER À KITT",

    // Hero
    "hero.label": "KNIGHT INDUSTRIES TWO THOUSAND — SYSTÈME KYRONEX",
    "hero.tagline": "Intelligence artificielle locale expérimentale",
    "hero.subtitle": "Projet passionnel & non commercial — par",
    "hero.cta1": "ACCÉDER À L'INTERFACE",
    "hero.cta2": "DÉCOUVRIR LE PROJET",
    "hero.members": "MEMBRES",
    "hero.status": "ONLINE",

    // Story
    "story.label": "// DOSSIER_01 — HISTOIRE DU PROJET",
    "story.title1": "L'HISTOIRE DE",
    "story.title2": "KITT FRANCO-BELGE",
    "story.genesis": "GENÈSE DU PROJET",
    "story.p1": "Le projet KITT Franco-Belge est une initiative personnelle et expérimentale dédiée au développement d'une intelligence artificielle locale fonctionnant sur architecture Jetson AJX 32/64.",
    "story.p2": "Né de la passion pour la série télévisée Knight Rider (K2000), ce projet transcende le simple hommage pour devenir une véritable plateforme technologique. Emmanuel Gelinne, alias Manix, y consacre son expertise en électronique embarquée et en intelligence artificielle.",
    "story.p3": "Le système évolue en continu : certaines améliorations sont déployées chaque jour, d'autres chaque semaine. Lors de phases expérimentales, des changements peuvent apparaître presque heure par heure. Revenir régulièrement permet de suivre l'évolution réelle du système.",
    "story.stat1": "MEMBRES",
    "story.stat2": "EN LIGNE",
    "story.stat3": "ÉVOLUTION",
    "story.scanner": "SCANNER K.I.T.T. — SIGNATURE VISUELLE",
    "story.sheet": "// FICHE SYSTÈME",
    "story.key.projet": "PROJET",
    "story.key.auteur": "AUTEUR",
    "story.key.arch": "ARCHITECTURE",
    "story.key.statut": "STATUT",
    "story.key.cadre": "CADRE",
    "story.key.licence": "LICENCE",
    "story.val.statut": "CONSTRUCTION ACTIVE",
    "story.val.cadre": "Non commercial / Passionnel",
    "story.val.licence": "Propriétaire — Tous droits réservés",
    "story.legal": "// CADRE JURIDIQUE",
    "story.legal.text": "Ce projet constitue une création originale indépendante. L'ensemble du code, de l'architecture logicielle, du design et des contenus techniques est protégé par le droit d'auteur. Toute reproduction ou exploitation commerciale sans autorisation écrite préalable est formellement interdite. Les éventuelles références à des univers de fiction sont utilisées dans un contexte descriptif et non officiel.",

    // Services
    "services.label": "// DOSSIER_02 — CAPACITÉS SYSTÈME",
    "services.title1": "MODULES &",
    "services.title2": "SERVICES",
    "services.0.title": "Intelligence Artificielle Locale",
    "services.0.subtitle": "KYRONEX A.I. System",
    "services.0.desc": "Développement d'une IA locale expérimentale fonctionnant sur architecture Jetson AJX 32/64. Traitement autonome, sans dépendance cloud, pour une réactivité maximale.",
    "services.1.title": "Interface Publique KITT",
    "services.1.subtitle": "Système Central en Ligne",
    "services.1.desc": "La première interface publique du projet KITT Franco-Belge est accessible en ligne. Évolution continue : améliorations déployées quotidiennement, parfois heure par heure. Disponible tous les jours de 08h00 à 23h00.",
    "services.2.title": "Navigation & Détection",
    "services.2.subtitle": "GPS + Radar Fix",
    "services.2.desc": "Intégration GPS avancée et détection radar via fichiers CSV nationaux. Système de navigation autonome inspiré des capacités de K.I.T.T. de la série Knight Rider.",
    "services.3.title": "Électronique Embarquée",
    "services.3.subtitle": "Convertisseur DC-DC & Console",
    "services.3.desc": "Conception et test de systèmes électroniques embarqués : convertisseur DC-DC 12,4V stable, protection contre les surtensions, nouvelle console haute Pascal K industrie / Vincenzo Forte.",
    "services.4.title": "Base de Données Vidéo",
    "services.4.subtitle": "Archive Internationale",
    "services.4.desc": "Constitution d'une base de données vidéo internationale multilingue dédiée à la naissance et à la création du nouveau KITT K2000. Documentation exhaustive du projet.",
    "services.5.title": "Réplique & Restauration",
    "services.5.subtitle": "Pontiac Trans Am",
    "services.5.desc": "Projet de réplique fidèle de K.I.T.T. sur base Pontiac Trans Am. Travail artisanal passionnel alliant authenticité technique et respect de l'univers Knight Rider.",

    // Progression
    "progression.label": "// DIAGNOSTIC — ÉTAT DU PROJET",
    "progression.title1": "PROGRESSION",
    "progression.title2": "DU SYSTÈME",
    "progression.0.label": "Scanner K.I.T.T.",
    "progression.0.tag": "COMPLET",
    "progression.1.label": "Intelligence Artificielle KYRONEX",
    "progression.1.tag": "EN LIGNE",
    "progression.2.label": "Carrosserie Extérieure",
    "progression.2.tag": "EN COURS",
    "progression.3.label": "Dashboard Knight Rider S4",
    "progression.3.tag": "EN COURS",
    "progression.4.label": "Électronique Embarquée",
    "progression.4.tag": "EN COURS",
    "progression.5.label": "Pare-choc KARR",
    "progression.5.tag": "EN COURS",

    // Videos section
    "videossec.label": "// DOSSIER_03 — ARCHIVES VIDÉO",
    "videossec.title1": "CHAÎNE YOUTUBE",
    "videossec.title2": "KITT FRANCO-BELGE",
    "videossec.cta1": "VOIR TOUTES LES VIDÉOS",
    "videossec.cta2": "S'ABONNER À LA CHAÎNE",
    "videos.0.title": "Kitt Franco Belge",
    "videos.0.desc": "Présentation générale du projet KITT sur base Pontiac Firebird.",
    "videos.1.title": "Alternateur Firebird",
    "videos.1.desc": "Réparation d'un alternateur CS130 ACDelco Remy — démontage, diagnostic et essais.",
    "videos.2.title": "Rassemblement Voitures de Films — Sazilly",
    "videos.2.desc": "Incroyable rassemblement de voitures de films et séries télévisées.",
    "videos.3.title": "K2000 — 16 secondes de merci",
    "videos.3.desc": "Un immense merci aux membres du groupe pour leur expertise et leur soutien.",
    "videos.4.title": "KARR — Pare-choc mise en peinture",
    "videos.4.desc": "Avancement de la mise en peinture du pare-choc style KARR (Knight Rider 1982).",
    "videos.5.title": "Progression générale du projet",
    "videos.5.desc": "Aperçu intérieur & extérieur : dashboard Knight Rider S4, ponçage et peinture.",

    // Community
    "community.label": "// DOSSIER_03 — RETOURS COMMUNAUTÉ",
    "community.title1": "CE QUE DIT",
    "community.title2": "LA COMMUNAUTÉ",
    "community.stat1": "MEMBRES FACEBOOK",
    "community.stat2": "RÉACTIONS / POST",
    "community.stat3": "COMMENTAIRES",
    "community.stat4": "PASSION",
    "community.cta1": "VOIR LE GROUPE",
    "community.cta2": "REJOINDRE LE GROUPE",
    "reviews.0.text": "Ça va mieux Manu ! Le projet avance vraiment bien, on voit l'évolution chaque semaine. Impressionnant le travail accompli.",
    "reviews.0.date": "Il y a 3 semaines",
    "reviews.1.text": "K2000 ! Bonjour — le projet est incroyable, ça ressemble vraiment à KITT. Le scanner est bluffant de réalisme !",
    "reviews.1.date": "Il y a 1 semaine",
    "reviews.2.text": "KRMEX ressort légèrement, on dirait... La qualité de la réplique est vraiment au niveau. Bravo pour ce travail de passionné.",
    "reviews.2.date": "Il y a 1 semaine",
    "reviews.3.text": "La première interface du projet KITT Franco-Belge est désormais accessible en ligne. Une initiative remarquable dans la communauté francophone.",
    "reviews.3.date": "Récemment",

    // Contact
    "contact.label": "// DOSSIER_04 — COMMUNICATION",
    "contact.title1": "TRANSMETTRE UN",
    "contact.title2": "MESSAGE",
    "contact.desc": "Pour toute demande de collaboration, question technique, ou souhait d'accès à l'interface KITT, contactez directement Emmanuel Gelinne (Manix) via ce formulaire ou les réseaux sociaux.",
    "contact.access": "Code d'accès sur demande (MP Facebook)",
    "contact.system": "// ÉTAT DU SYSTÈME",
    "contact.kyronex": "KYRONEX : EN CONSTRUCTION",
    "contact.facebook": "FACEBOOK : ACTIF — 5K+ MEMBRES",
    "contact.form": "// FORMULAIRE DE TRANSMISSION",
    "contact.name": "NOM *",
    "contact.email": "EMAIL *",
    "contact.subject": "SUJET",
    "contact.message": "MESSAGE *",
    "contact.name.ph": "Votre nom",
    "contact.subject.ph": "Objet du message",
    "contact.message.ph": "Votre message...",
    "contact.send": "TRANSMETTRE LE MESSAGE",
    "contact.sending": "TRANSMISSION EN COURS...",
    "contact.success": "Message transmis au système KITT. Réponse en cours de traitement...",
    "contact.error": "Erreur de transmission. Réessaie dans un instant.",
    "contact.required": "Veuillez remplir tous les champs obligatoires.",

    // Footer
    "footer.brand": "Intelligence artificielle locale expérimentale. Projet passionnel non commercial par Emmanuel Gelinne (Manix).",
    "footer.nav": "NAVIGATION",
    "footer.external": "LIENS EXTERNES",
    "footer.nav.1": "Histoire du projet",
    "footer.nav.2": "Modules & Services",
    "footer.nav.3": "Communauté",
    "footer.nav.4": "Contact",
    "footer.ext.1": "Interface KITT (KYRONEX)",
    "footer.ext.2": "Groupe Facebook",
    "footer.ext.3": "Chaine YouTube KITT K2000",
    "footer.copy": "© 2026 KITT FRANCO-BELGE — Emmanuel Gelinne (Manix) — Tous droits réservés",

    // Visitor counter
    "counter.label": "// SYSTÈME KYRONEX — ACCÈS ENREGISTRÉS",
    "counter.sub": "COMPTEUR GLOBAL · VISITEURS UNIQUES",
    "counter.online": "● SYSTÈME EN LIGNE",
    "counter.new": "BIENVENUE — ACCÈS AUTORISÉ",
    "counter.known": "ACCÈS RECONNU",

    // Subscribe popup
    "popup.label": "// SYSTÈME KYRONEX — NOTIFICATION",
    "popup.title": "Tu suis le projet KITT ?",
    "popup.highlight": "Abonne-toi à la chaîne !",
    "popup.desc": "Nouvelles vidéos chaque semaine — construction, électronique, KARR...",
    "popup.cta": "▶ S'ABONNER MAINTENANT",

    // Videos page
    "videospage.sys": "// SYSTÈME KITT FRANCO-BELGE — GALERIE VIDÉO",
    "videospage.title": "VIDÉOS",
    "videospage.subtitle": "SÉLECTIONNÉES PAR MANIX",
    "videospage.desc": "Vidéos liées au projet KITT Franco-Belge, sélectionnées et approuvées par Manix. Tu peux",
    "videospage.submit.link": "soumettre une vidéo",
    "videospage.desc2": "si tu en as une.",
    "videospage.loading": "// CHARGEMENT EN COURS...",
    "videospage.offline": "[HORS LIGNE]",
    "videospage.offline.msg": "Le système KITT est temporairement hors ligne. Réessaie plus tard.",
    "videospage.empty": "// AUCUNE VIDÉO",
    "videospage.empty.msg": "Aucune vidéo n'a encore été approuvée.",
    "videospage.empty.first": "Soumettre la première ?",
    "videospage.cta.submit": "▶ SOUMETTRE UNE VIDÉO",
    "videospage.cta.back": "← RETOUR AU SYSTÈME KITT",

    // Soumettre page
    "soumettre.sys": "// SYSTÈME KITT FRANCO-BELGE — SOUMISSION VIDÉO",
    "soumettre.title": "SOUMETTRE",
    "soumettre.subtitle": "UNE VIDÉO",
    "soumettre.desc": "Tu as trouvé une vidéo liée au projet KITT Franco-Belge ? Partage-la ici. Manix la recevra et décidera de l'ajouter ou non à la galerie officielle.",
    "soumettre.success.label": "// TRANSMISSION REÇUE",
    "soumettre.success.msg": "Vidéo soumise avec succès. Manix recevra une notification et examinera ta soumission.",
    "soumettre.success.btn": "SOUMETTRE UNE AUTRE",
    "soumettre.url.label": "// LIEN VIDÉO (YouTube ou Facebook) *",
    "soumettre.url.ph": "https://www.youtube.com/watch?v=... ou https://fb.watch/...",
    "soumettre.pseudo.label": "// TON PSEUDO (optionnel)",
    "soumettre.pseudo.ph": "Anonyme",
    "soumettre.msg.label": "// MESSAGE (optionnel)",
    "soumettre.msg.ph": "Pourquoi cette vidéo mérite-t-elle d'être ajoutée ?",
    "soumettre.send": "▶ ENVOYER LA VIDÉO",
    "soumettre.sending": "TRANSMISSION EN COURS...",
    "soumettre.back": "← RETOUR AU SYSTÈME KITT",

    // Musique page
    "musique.sys": "// SYSTÈME KITT FRANCO-BELGE — LECTEUR AUDIO",
    "musique.title": "MUSIQUE",
    "musique.subtitle": "SÉLECTIONNÉE PAR MANIX",
    "musique.desc": "Musiques liées au projet KITT Franco-Belge, approuvées par Manix.",
    "musique.submit.link": "Soumettre un morceau",
    "musique.loading": "// CHARGEMENT...",
    "musique.offline": "Système hors ligne",
    "musique.empty": "Aucune musique approuvée pour l'instant.",
    "musique.submit.first": "Soumettre la première ?",
    "musique.plays": "écoutes",
    "musique.cta.submit": "▶ SOUMETTRE UN MORCEAU",
    "musique.cta.back": "← RETOUR AU SYSTÈME KITT",

    // Soumettre Musique
    "soumettremusique.sys": "// SYSTÈME KITT FRANCO-BELGE — SOUMISSION AUDIO",
    "soumettremusique.title": "SOUMETTRE",
    "soumettremusique.subtitle": "UN MORCEAU",
    "soumettremusique.desc": "Tu as un morceau lié à l'univers KITT ou Knight Rider ? Partage-le ici. Manix examinera ta soumission.",
    "soumettremusique.url.label": "// LIEN MP3 DIRECT *",
    "soumettremusique.url.ph": "https://files.catbox.moe/xxxxx.mp3",
    "soumettremusique.titre.label": "// TITRE *",
    "soumettremusique.titre.ph": "Nom du morceau",
    "soumettremusique.artiste.label": "// ARTISTE (optionnel)",
    "soumettremusique.artiste.ph": "Anonyme",
    "soumettremusique.send": "▶ ENVOYER LE MORCEAU",
    "soumettremusique.sending": "TRANSMISSION EN COURS...",
    "soumettremusique.success.label": "// TRANSMISSION REÇUE",
    "soumettremusique.success.msg": "Morceau soumis avec succès. Manix le recevra et décidera de l'ajouter.",
    "soumettremusique.success.btn": "SOUMETTRE UN AUTRE",
    "soumettremusique.back": "← RETOUR AU SYSTÈME KITT",

    // Pdfs page
    "pdfs.sys": "// SYSTÈME KITT FRANCO-BELGE — BIBLIOTHÈQUE",
    "pdfs.title": "DOCUMENTS",
    "pdfs.subtitle": "BIBLIOTHÈQUE PDF",
    "pdfs.desc": "Documents techniques, guides et archives liés au projet KITT Franco-Belge.",
    "pdfs.submit.link": "Soumettre un document",
    "pdfs.loading": "// CHARGEMENT...",
    "pdfs.offline": "Système hors ligne",
    "pdfs.empty": "Aucun document approuvé pour l'instant.",
    "pdfs.submit.first": "Soumettre le premier ?",
    "pdfs.views": "vues",
    "pdfs.open": "OUVRIR",
    "pdfs.cta.submit": "▶ SOUMETTRE UN DOCUMENT",
    "pdfs.cta.back": "← RETOUR AU SYSTÈME KITT",

    // Soumettre PDF
    "soumettrepdf.sys": "// SYSTÈME KITT FRANCO-BELGE — SOUMISSION DOCUMENT",
    "soumettrepdf.title": "SOUMETTRE",
    "soumettrepdf.subtitle": "UN DOCUMENT",
    "soumettrepdf.desc": "Tu as un document lié au projet KITT ou Knight Rider ? Partage-le ici.",
    "soumettrepdf.url.label": "// LIEN PDF DIRECT *",
    "soumettrepdf.url.ph": "https://example.com/document.pdf",
    "soumettrepdf.titre.label": "// TITRE *",
    "soumettrepdf.titre.ph": "Nom du document",
    "soumettrepdf.categorie.label": "// CATÉGORIE",
    "soumettrepdf.desc2.label": "// DESCRIPTION (optionnel)",
    "soumettrepdf.desc2.ph": "Décris brièvement ce document...",
    "soumettrepdf.send": "▶ ENVOYER LE DOCUMENT",
    "soumettrepdf.sending": "TRANSMISSION EN COURS...",
    "soumettrepdf.success.label": "// TRANSMISSION REÇUE",
    "soumettrepdf.success.msg": "Document soumis avec succès. Manix l'examinera.",
    "soumettrepdf.success.btn": "SOUMETTRE UN AUTRE",
    "soumettrepdf.back": "← RETOUR AU SYSTÈME KITT",
  },

  en: {
    // Nav
    "nav.histoire": "history",
    "nav.services": "services",
    "nav.videos": "videos",
    "nav.avis": "reviews",
    "nav.contact": "contact",
    "nav.karr": "KARR",
    "nav.soumettre": "SUBMIT",
    "nav.galerie": "GALLERY",
    "nav.musique": "MUSIC",
    "nav.docs": "DOCS",
    "nav.access": "ACCESS KITT",

    // Hero
    "hero.label": "KNIGHT INDUSTRIES TWO THOUSAND — KYRONEX SYSTEM",
    "hero.tagline": "Experimental local artificial intelligence",
    "hero.subtitle": "Passion project & non-commercial — by",
    "hero.cta1": "ACCESS THE INTERFACE",
    "hero.cta2": "DISCOVER THE PROJECT",
    "hero.members": "MEMBERS",
    "hero.status": "ONLINE",

    // Story
    "story.label": "// FILE_01 — PROJECT HISTORY",
    "story.title1": "THE STORY OF",
    "story.title2": "KITT FRANCO-BELGE",
    "story.genesis": "PROJECT GENESIS",
    "story.p1": "The KITT Franco-Belge project is a personal and experimental initiative dedicated to developing a local artificial intelligence running on Jetson AJX 32/64 architecture.",
    "story.p2": "Born from a passion for the TV series Knight Rider (K2000), this project goes beyond a simple tribute to become a true technology platform. Emmanuel Gelinne, aka Manix, dedicates his expertise in embedded electronics and artificial intelligence to it.",
    "story.p3": "The system evolves continuously: some improvements are deployed every day, others every week. During experimental phases, changes can appear almost every hour. Check back regularly to follow the real evolution of the system.",
    "story.stat1": "MEMBERS",
    "story.stat2": "ONLINE",
    "story.stat3": "EVOLUTION",
    "story.scanner": "K.I.T.T. SCANNER — VISUAL SIGNATURE",
    "story.sheet": "// SYSTEM SHEET",
    "story.key.projet": "PROJECT",
    "story.key.auteur": "AUTHOR",
    "story.key.arch": "ARCHITECTURE",
    "story.key.statut": "STATUS",
    "story.key.cadre": "FRAMEWORK",
    "story.key.licence": "LICENSE",
    "story.val.statut": "ACTIVE BUILD",
    "story.val.cadre": "Non-commercial / Passion",
    "story.val.licence": "Proprietary — All rights reserved",
    "story.legal": "// LEGAL FRAMEWORK",
    "story.legal.text": "This project is an independent original creation. All code, software architecture, design and technical content is protected by copyright. Any reproduction or commercial exploitation without prior written authorization is strictly prohibited. Any references to fictional universes are used in a descriptive and unofficial context.",

    // Services
    "services.label": "// FILE_02 — SYSTEM CAPABILITIES",
    "services.title1": "MODULES &",
    "services.title2": "SERVICES",
    "services.0.title": "Local Artificial Intelligence",
    "services.0.subtitle": "KYRONEX A.I. System",
    "services.0.desc": "Development of an experimental local AI running on Jetson AJX 32/64 architecture. Autonomous processing, without cloud dependency, for maximum responsiveness.",
    "services.1.title": "KITT Public Interface",
    "services.1.subtitle": "Central System Online",
    "services.1.desc": "The first public interface of the KITT Franco-Belge project is accessible online. Continuous evolution: improvements deployed daily, sometimes hour by hour. Available every day from 08:00 to 23:00.",
    "services.2.title": "Navigation & Detection",
    "services.2.subtitle": "GPS + Radar Fix",
    "services.2.desc": "Advanced GPS integration and radar detection via national CSV files. Autonomous navigation system inspired by K.I.T.T.'s capabilities from the Knight Rider series.",
    "services.3.title": "Embedded Electronics",
    "services.3.subtitle": "DC-DC Converter & Console",
    "services.3.desc": "Design and testing of embedded electronic systems: stable 12.4V DC-DC converter, overvoltage protection, new high Pascal K industrial console / Vincenzo Forte.",
    "services.4.title": "Video Database",
    "services.4.subtitle": "International Archive",
    "services.4.desc": "Building a multilingual international video database dedicated to the birth and creation of the new KITT K2000. Comprehensive project documentation.",
    "services.5.title": "Replica & Restoration",
    "services.5.subtitle": "Pontiac Trans Am",
    "services.5.desc": "Faithful replica project of K.I.T.T. based on a Pontiac Trans Am. Passionate craftsmanship combining technical authenticity and respect for the Knight Rider universe.",

    // Progression
    "progression.label": "// DIAGNOSTIC — PROJECT STATUS",
    "progression.title1": "SYSTEM",
    "progression.title2": "PROGRESS",
    "progression.0.label": "K.I.T.T. Scanner",
    "progression.0.tag": "COMPLETE",
    "progression.1.label": "KYRONEX Artificial Intelligence",
    "progression.1.tag": "ONLINE",
    "progression.2.label": "Exterior Body",
    "progression.2.tag": "IN PROGRESS",
    "progression.3.label": "Knight Rider S4 Dashboard",
    "progression.3.tag": "IN PROGRESS",
    "progression.4.label": "Embedded Electronics",
    "progression.4.tag": "IN PROGRESS",
    "progression.5.label": "KARR Front Bumper",
    "progression.5.tag": "IN PROGRESS",

    // Videos section
    "videossec.label": "// FILE_03 — VIDEO ARCHIVES",
    "videossec.title1": "YOUTUBE CHANNEL",
    "videossec.title2": "KITT FRANCO-BELGE",
    "videossec.cta1": "SEE ALL VIDEOS",
    "videossec.cta2": "SUBSCRIBE TO CHANNEL",
    "videos.0.title": "Kitt Franco Belge",
    "videos.0.desc": "General overview of the KITT project based on a Pontiac Firebird.",
    "videos.1.title": "Firebird Alternator",
    "videos.1.desc": "CS130 ACDelco Remy alternator repair — disassembly, diagnosis and testing.",
    "videos.2.title": "Movie Cars Rally — Sazilly",
    "videos.2.desc": "Amazing gathering of movie and TV series cars.",
    "videos.3.title": "K2000 — 16 seconds of thanks",
    "videos.3.desc": "A huge thank you to group members for their expertise and support.",
    "videos.4.title": "KARR — Bumper painting",
    "videos.4.desc": "Progress on the KARR-style bumper paint (Knight Rider 1982).",
    "videos.5.title": "General project progress",
    "videos.5.desc": "Interior & exterior overview: Knight Rider S4 dashboard, sanding and paint.",

    // Community
    "community.label": "// FILE_03 — COMMUNITY FEEDBACK",
    "community.title1": "WHAT THE",
    "community.title2": "COMMUNITY SAYS",
    "community.stat1": "FACEBOOK MEMBERS",
    "community.stat2": "REACTIONS / POST",
    "community.stat3": "COMMENTS",
    "community.stat4": "PASSION",
    "community.cta1": "VIEW THE GROUP",
    "community.cta2": "JOIN THE GROUP",
    "reviews.0.text": "Getting better Manu! The project is really moving forward, you can see the evolution every week. The work accomplished is impressive.",
    "reviews.0.date": "3 weeks ago",
    "reviews.1.text": "K2000! Hello — the project is incredible, it really looks like KITT. The scanner is stunningly realistic!",
    "reviews.1.date": "1 week ago",
    "reviews.2.text": "KRMEX looks slightly different, it seems... The quality of the replica is really up there. Bravo for this passionate work.",
    "reviews.2.date": "1 week ago",
    "reviews.3.text": "The first interface of the KITT Franco-Belge project is now accessible online. A remarkable initiative in the French-speaking community.",
    "reviews.3.date": "Recently",

    // Contact
    "contact.label": "// FILE_04 — COMMUNICATION",
    "contact.title1": "SEND A",
    "contact.title2": "MESSAGE",
    "contact.desc": "For any collaboration request, technical question, or wish to access the KITT interface, contact Emmanuel Gelinne (Manix) directly via this form or social networks.",
    "contact.access": "Access code on request (Facebook DM)",
    "contact.system": "// SYSTEM STATUS",
    "contact.kyronex": "KYRONEX: UNDER CONSTRUCTION",
    "contact.facebook": "FACEBOOK: ACTIVE — 5K+ MEMBERS",
    "contact.form": "// TRANSMISSION FORM",
    "contact.name": "NAME *",
    "contact.email": "EMAIL *",
    "contact.subject": "SUBJECT",
    "contact.message": "MESSAGE *",
    "contact.name.ph": "Your name",
    "contact.subject.ph": "Message subject",
    "contact.message.ph": "Your message...",
    "contact.send": "SEND MESSAGE",
    "contact.sending": "TRANSMITTING...",
    "contact.success": "Message transmitted to the KITT system. Response being processed...",
    "contact.error": "Transmission error. Please try again in a moment.",
    "contact.required": "Please fill in all required fields.",

    // Footer
    "footer.brand": "Experimental local artificial intelligence. Non-commercial passion project by Emmanuel Gelinne (Manix).",
    "footer.nav": "NAVIGATION",
    "footer.external": "EXTERNAL LINKS",
    "footer.nav.1": "Project history",
    "footer.nav.2": "Modules & Services",
    "footer.nav.3": "Community",
    "footer.nav.4": "Contact",
    "footer.ext.1": "KITT Interface (KYRONEX)",
    "footer.ext.2": "Facebook Group",
    "footer.ext.3": "KITT K2000 YouTube Channel",
    "footer.copy": "© 2026 KITT FRANCO-BELGE — Emmanuel Gelinne (Manix) — All rights reserved",

    // Visitor counter
    "counter.label": "// KYRONEX SYSTEM — REGISTERED ACCESS",
    "counter.sub": "GLOBAL COUNTER · UNIQUE VISITORS",
    "counter.online": "● SYSTEM ONLINE",
    "counter.new": "WELCOME — ACCESS GRANTED",
    "counter.known": "ACCESS RECOGNIZED",

    // Subscribe popup
    "popup.label": "// KYRONEX SYSTEM — NOTIFICATION",
    "popup.title": "Following the KITT project?",
    "popup.highlight": "Subscribe to the channel!",
    "popup.desc": "New videos every week — build, electronics, KARR...",
    "popup.cta": "▶ SUBSCRIBE NOW",

    // Videos page
    "videospage.sys": "// KITT FRANCO-BELGE SYSTEM — VIDEO GALLERY",
    "videospage.title": "VIDEOS",
    "videospage.subtitle": "SELECTED BY MANIX",
    "videospage.desc": "Videos related to the KITT Franco-Belge project, selected and approved by Manix. You can",
    "videospage.submit.link": "submit a video",
    "videospage.desc2": "if you have one.",
    "videospage.loading": "// LOADING...",
    "videospage.offline": "[OFFLINE]",
    "videospage.offline.msg": "The KITT system is temporarily offline. Try again later.",
    "videospage.empty": "// NO VIDEOS",
    "videospage.empty.msg": "No videos have been approved yet.",
    "videospage.empty.first": "Submit the first one?",
    "videospage.cta.submit": "▶ SUBMIT A VIDEO",
    "videospage.cta.back": "← BACK TO KITT SYSTEM",

    // Soumettre page
    "soumettre.sys": "// KITT FRANCO-BELGE SYSTEM — VIDEO SUBMISSION",
    "soumettre.title": "SUBMIT",
    "soumettre.subtitle": "A VIDEO",
    "soumettre.desc": "Found a video related to the KITT Franco-Belge project? Share it here. Manix will receive it and decide whether to add it to the official gallery.",
    "soumettre.success.label": "// TRANSMISSION RECEIVED",
    "soumettre.success.msg": "Video submitted successfully. Manix will receive a notification and review your submission.",
    "soumettre.success.btn": "SUBMIT ANOTHER",
    "soumettre.url.label": "// VIDEO LINK (YouTube or Facebook) *",
    "soumettre.url.ph": "https://www.youtube.com/watch?v=... or https://fb.watch/...",
    "soumettre.pseudo.label": "// YOUR NICKNAME (optional)",
    "soumettre.pseudo.ph": "Anonymous",
    "soumettre.msg.label": "// MESSAGE (optional)",
    "soumettre.msg.ph": "Why does this video deserve to be added?",
    "soumettre.send": "▶ SEND THE VIDEO",
    "soumettre.sending": "TRANSMITTING...",
    "soumettre.back": "← BACK TO KITT SYSTEM",

    // Musique page
    "musique.sys": "// KITT FRANCO-BELGE SYSTEM — AUDIO PLAYER",
    "musique.title": "MUSIC",
    "musique.subtitle": "SELECTED BY MANIX",
    "musique.desc": "Music related to the KITT Franco-Belge project, approved by Manix.",
    "musique.submit.link": "Submit a track",
    "musique.loading": "// LOADING...",
    "musique.offline": "System offline",
    "musique.empty": "No approved music yet.",
    "musique.submit.first": "Submit the first one?",
    "musique.plays": "plays",
    "musique.cta.submit": "▶ SUBMIT A TRACK",
    "musique.cta.back": "← BACK TO KITT SYSTEM",

    // Soumettre Musique
    "soumettremusique.sys": "// KITT FRANCO-BELGE SYSTEM — AUDIO SUBMISSION",
    "soumettremusique.title": "SUBMIT",
    "soumettremusique.subtitle": "A TRACK",
    "soumettremusique.desc": "Have a track related to the KITT or Knight Rider universe? Share it here. Manix will review your submission.",
    "soumettremusique.url.label": "// DIRECT MP3 LINK *",
    "soumettremusique.url.ph": "https://files.catbox.moe/xxxxx.mp3",
    "soumettremusique.titre.label": "// TITLE *",
    "soumettremusique.titre.ph": "Track name",
    "soumettremusique.artiste.label": "// ARTIST (optional)",
    "soumettremusique.artiste.ph": "Anonymous",
    "soumettremusique.send": "▶ SEND THE TRACK",
    "soumettremusique.sending": "TRANSMITTING...",
    "soumettremusique.success.label": "// TRANSMISSION RECEIVED",
    "soumettremusique.success.msg": "Track submitted successfully. Manix will receive it and decide whether to add it.",
    "soumettremusique.success.btn": "SUBMIT ANOTHER",
    "soumettremusique.back": "← BACK TO KITT SYSTEM",

    // Pdfs page
    "pdfs.sys": "// KITT FRANCO-BELGE SYSTEM — LIBRARY",
    "pdfs.title": "DOCUMENTS",
    "pdfs.subtitle": "PDF LIBRARY",
    "pdfs.desc": "Technical documents, guides and archives related to the KITT Franco-Belge project.",
    "pdfs.submit.link": "Submit a document",
    "pdfs.loading": "// LOADING...",
    "pdfs.offline": "System offline",
    "pdfs.empty": "No approved documents yet.",
    "pdfs.submit.first": "Submit the first one?",
    "pdfs.views": "views",
    "pdfs.open": "OPEN",
    "pdfs.cta.submit": "▶ SUBMIT A DOCUMENT",
    "pdfs.cta.back": "← BACK TO KITT SYSTEM",

    // Soumettre PDF
    "soumettrepdf.sys": "// KITT FRANCO-BELGE SYSTEM — DOCUMENT SUBMISSION",
    "soumettrepdf.title": "SUBMIT",
    "soumettrepdf.subtitle": "A DOCUMENT",
    "soumettrepdf.desc": "Have a document related to the KITT project or Knight Rider? Share it here.",
    "soumettrepdf.url.label": "// DIRECT PDF LINK *",
    "soumettrepdf.url.ph": "https://example.com/document.pdf",
    "soumettrepdf.titre.label": "// TITLE *",
    "soumettrepdf.titre.ph": "Document name",
    "soumettrepdf.categorie.label": "// CATEGORY",
    "soumettrepdf.desc2.label": "// DESCRIPTION (optional)",
    "soumettrepdf.desc2.ph": "Briefly describe this document...",
    "soumettrepdf.send": "▶ SEND THE DOCUMENT",
    "soumettrepdf.sending": "TRANSMITTING...",
    "soumettrepdf.success.label": "// TRANSMISSION RECEIVED",
    "soumettrepdf.success.msg": "Document submitted successfully. Manix will review it.",
    "soumettrepdf.success.btn": "SUBMIT ANOTHER",
    "soumettrepdf.back": "← BACK TO KITT SYSTEM",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("kitt_lang") as Lang | null;
    if (saved === "fr" || saved === "en") return saved;
    const browser = navigator.language.toLowerCase();
    return browser.startsWith("fr") ? "fr" : "en";
  });

  const toggle = () => {
    const next: Lang = lang === "fr" ? "en" : "fr";
    setLang(next);
    localStorage.setItem("kitt_lang", next);
  };

  const t = (key: string): string => translations[lang][key] ?? translations["fr"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
